{% set version = "1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rook
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rook_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rook/Rook_{{ version }}.tar.gz
  sha256: c79ae4b5164daffd4e7cf74bd23c1b08a3948bf343dfe9570d57f39cbf8e5f62

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-brew
  run:
    - r-base
    - r-brew

test:
  commands:
    - $R -e "library('Rook')"           # [not win]
    - "\"%R%\" -e \"library('Rook')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Rook
  license: GPL-2.0-only
  summary: An HTTP web server for R with a documented API to interface between R and the server.
    The documentation contains the Rook specification and details for building and running
    Rook applications. To get started, be sure and read the 'Rook' help file first.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
