{% set version = "1.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rook
  version: {{ version|replace("-", "_") }}

source:
  fn: Rook_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/Rook_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rook/Rook_{{ version }}.tar.gz
  sha256: c79ae4b5164daffd4e7cf74bd23c1b08a3948bf343dfe9570d57f39cbf8e5f62

build:
  merge_build_host: true  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-brew

  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-brew

test:
  commands:
    - $R -e "library('Rook')"           # [not win]
    - "\"%R%\" -e \"library('Rook')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Rook
  license: GPL-2
  summary: |
    This package contains the Rook specification and convenience software for building
    and running Rook applications. To get started, be sure and read the 'Rook' help
    file first.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
