# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FX0hsGedtDJK4klcAKGtFbaa1g1OX8wFa6nTNejsXKU+p6d4vMf3XK5e9JRq3hcVT1rPKLijImBqQjpDYoALLRJZOPkB42iZWrSHOqEJoH4nn1xOXm6eqSPmUmo3s9KCjIuVGx8l8BvMxqOCI/sFPnwPeFRwFLqATOYXfddJNrIOFhCwEFuw0x/tqrR0UQO0lGcbwiX4UO9GubYhNyM3OfnAwgGWlPiwS4tVO6KwUpxDSDM7yg/qYtxeZDUZW1/nsHCsEmpBrMMrtk7GhpWugnr0nHzqPxsxIvC6Bjc9V/YTXxi/QQVRz2YjzqF9JpbDIxIchB4odspYJmxPuGHAeAV2uoo2RzhN9x6svpjcE2pwEixquBa0zB/Gwfh4RkbOjZr02qO6qAtoN2oginjQg6J30wKXkx7dJdkAkPJkPjm+NaH1PMy5tF0z/tmsFGqSmFoo6gaWPyxlr/OLvYLKzN8udwhtKAiKtxiCeX2PKOenKj2nor2JnV3lGeF2FgWyzDVr/FdD+1LPr9WiCnd5eW57T0lKN9sbnX3Gz/92SXBYSA5Wd9Rlj/WFbUVURa4peterdHy6/CX0bIFg/+fPr6Hi/qkDVpx2f3xE8gO0te5FpV+Li+vfCg0GYicyx0sh0juDYzZ6Jh4bdvYvmhs5FjxPeeAS+xXVrb4R/JCJZg8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
